while True:
    try:
        horario = input()
        
        hora, minuto = horario.split(":")
        hora = str((bin(int(hora)))[2:].zfill(4))
        minuto = str((bin(int(minuto)))[2:].zfill(6))
    
        print(" ____________________________________________")
        print("|                                            |")
        print("|    ____________________________________    |_")
        print("|   |                                    |   |_)")
        print("|   |   8         4         2         1  |   |")
        print("|   |                                    |   |")
        print("|   |   ",end="")
        if hora[0] == '1': print("o         ",end="")
        else:print("          ",end="")
        if hora[1] == '1': print("o         ",end="")
        else:print("          ",end="")
        if hora[2] == '1': print("o         ",end="")
        else:print("          ",end="")
        if hora[3] == '1': print("o  |   |")
        else:print("   |   |")
        print("|   |                                    |   |")
        print("|   |                                    |   |")
        print("|   |   ",end="")
        if minuto[0] == '1': print("o     ",end="")
        else:print("      ",end="")
        if minuto[1] == '1': print("o     ",end="")
        else:print("      ",end="")
        if minuto[2] == '1': print("o     ",end="")
        else:print("      ",end="")
        if minuto[3] == '1': print("o     ",end="")
        else:print("      ",end="")
        if minuto[4] == '1': print("o     ",end="")
        else:print("      ",end="")
        if minuto[5] == '1': print("o  |   |")
        else:print("   |   |")
        print("|   |                                    |   |")
        print("|   |   32    16    8     4     2     1  |   |_")
        print("|   |____________________________________|   |_)")
        print("|                                            |")
        print("|____________________________________________|")
        print()

    except EOFError:
        break
